require "soul.launch"
require "soul.core.options"
require "soul.core.keymaps"
require "soul.core.autocmds"
require "soul.core.tabline"
-- require "soul.core.cmpf"

-- GET "soul.plugins.oil"
-- GET "soul.plugins.catppuccin"
GET "soul.plugins.devicons"
-- GET "soul.plugins.treesitter"
GET "soul.plugins.schemastore"
GET "soul.plugins.telescope"
GET "soul.plugins.illuminate"
GET "soul.plugins.whichkey"
-- GET "soul.plugins.comment"
GET "soul.plugins.navic"
-- GET "soul.plugins.breadcrumbs"
GET "soul.plugins.harpoon"
-- GET "soul.plugins.neogit"
GET "soul.plugins.alpha"
-- GET "soul.plugins.project"
-- GET "soul.plugins.indentline"
GET "soul.plugins.toggleterm"
GET "soul.plugins.render_md"
GET "soul.plugins.mini"


GET "soul.lsp.lsp"
GET "soul.cmp.blink"

GET "soul.extras.noice"
GET "soul.extras.eyeliner"
GET "soul.extras.ufo"

require "soul.lazy"
require "soul.core.colors"
