require "soul.launch"
require "soul.core.options"
require "soul.core.keymaps"
require "soul.core.autocmds"

-- GET "soul.plugins.mini_files"
GET "soul.plugins.oil"
GET "soul.plugins.catppuccin"
GET "soul.plugins.devicons"
GET "soul.plugins.treesitter"
GET "soul.plugins.schemastore"
GET "soul.plugins.telescope"
GET "soul.plugins.illuminate"
GET "soul.plugins.gitsigns"
GET "soul.plugins.whichkey"
GET "soul.plugins.comment"
GET "soul.plugins.lualine"
GET "soul.plugins.navic"
GET "soul.plugins.breadcrumbs"
GET "soul.plugins.harpoon"
GET "soul.plugins.autopairs"
GET "soul.plugins.neogit"
GET "soul.plugins.alpha"
GET "soul.plugins.project"
GET "soul.plugins.indentline"
GET "soul.plugins.toggleterm"
GET "soul.plugins.render_md"


-- require("soul.lsp.lspconfig").config()
-- GET "soul.lsp.lspconfig"
-- GET "soul.lsp.mason"
-- GET "soul.cmp.main_cmp"
GET "soul.lsp.lsp"
GET "soul.cmp.blink"

-- GET "soul.exras.nvimtree"
-- GET "soul.extras.colorscheme"
GET "soul.extras.noice"
GET "soul.extras.eyeliner"
GET "soul.extras.ufo"

-- GET "soul.debug.none-ls"
-- GET "soul.debug.neotest"

require "soul.lazy"
require "soul.core.colors"
